BlogBundle_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

BlogBundle_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Blog:about }
    requirements:
        _method:  GET

BlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BlogBundle:Blog:contact }
    requirements:
        _method:  GET|POST

######################################################
BlogBundle_new:
    path: /new
    defaults: { _controller: BlogBundle:Blog:new }
    requirements:
        _method:  GET

BlogBundle_create:
    pattern:  /new/submit/
    defaults: { _controller: BlogBundle:Blog:create }


BlogBundle_show:
    pattern:  /{id}/
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

