BlogBundle\Entity\Comments:
    type: entity
    table: comments
    repositoryClass: BlogBundle\Entity\CommentsRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        pid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        comment:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        created:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
