BlogBundle\Entity\Users:
    type: entity
    table: users
    repositoryClass: BlogBundle\Entity\UsersRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            unique: true
        firstname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            unique: true
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        created:
            type: datetime
            nullable: false
            comment: ''
        lastlogin:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
